### ISSUE TITLE
Ranking IG

### ISSUE THREAD

**Issue by aerzy** [OpenNos/OpenNos#1116]
Ranking (Reput/Popularity etc..) IG not work :/

**Comment by 0Lucifer0** [comment]
It works... just gm are not in ranking

**Comment by aerzy** [comment]
Y i know i have player not gm and is not on ranking reput

**Comment by 0Lucifer0** [comment]
I have no problem It work great for me be sure to use a user account.

**Comment by Uppermost** [comment]
We need to see what is wrong on official all is right and same for NosTayle. (N4DE)

**Comment by Digitalis87** [comment]
On Official Reputation Ranking & Commends Ranking are uploaded every days (3 to 5 AM depending to the server).

**Comment by 0Lucifer0** [comment]
We upload it realtime. The problem is only client

**Comment by Uppermost** [comment]
No no we need to have a look at this worked fine before and I tried on nos4de it work for them and I use the same client.

**Comment by 0Lucifer0** [comment]
The problem is only the launcher... it works with a home made launcher

**Comment by Uppermost** [comment]
Yeah it work fine with a home made client oO wtf?

**Comment by Ciapa1** [comment]
I implemented them already years ago. Only Problem is: GM is not in
Ranking. Reputation and Commend ranking is ready, it Updates at every
connect. Point ranking is currently useless, as it is PVP, which is Far away

Am 03.11.2016 1:58 vorm. schrieb "Uppermost" <notifications@github.com>:

Assigned #1116 <https://github.com/OpenNos/OpenNos/issues/1116> to @Ciapa1
<https://github.com/Ciapa1>.

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/OpenNos/OpenNos/issues/1116#event-845819519>, or mute
the thread

**Comment by Uppermost** [comment]
I know GM are not on ranking but this server have 5000 player and I you see on screen always 3, but yes there is not refresh yet

**Comment by Ciapa1** [comment]
Will check locally.

**Comment by MasterDomino** [comment]
on other test server ive checked it and IG Ranking is alright, only other rankings doesnt work
