### ISSUE TITLE
Find a way to update the database whitout lose data

### ISSUE THREAD

**Issue by Uppermost** [OpenNos/OpenNos#1297]
We need to find a way to update the database whitout lose data, can be cool for everyone and for server private.

**Comment by DarkCacos** [comment]
I know that it might be difficult, but if you could also make a script to "clean" the maps when there is the problem of double NPC (Like those of Nosville and Krem, that after some events the ID of npc have changed and since I had to redo the parsing of some things, I now have those maps with double NPCs and need to delete the older manually...) possibly eliminating those in the same position or near (For the chicken) and obviously keep those inserted last into the database.

Screenshot of the problem: [Screenshot](https://s9.postimg.org/p26cnaf5r/20161020_2_Dark_Cacos.jpg)

**Comment by 0Lucifer0** [comment]
@DarkCacos don't post something on an other post if there is no similarity. For what you ask that's impossible. You are not supposed to copy past twice time packets. How to have a correct packet.txt : copy all past all run. If you want you can split all by "maps" and group them or replace them map by maps when needed.

**Comment by chucktheripper** [comment]
MSSQL

**Comment by 0Lucifer0** [comment]
Last update perhaps work with MySQL for migration ?

**Comment by chucktheripper** [comment]
Possible

**Comment by chucktheripper** [comment]
We need to try it with latest EF MySql binaries

**Comment by chucktheripper** [comment]
We moved to TSQL (MSSQL Server)
