### ISSUE TITLE
Wing of Angel with Packetlogger disconnects people

### ISSUE THREAD

**Issue by xKaddo** [OpenNos/OpenNos#1394]
Someone on my server was dropping Wing of Angel with a packetlogger. If you took the item, you got disconnected.

**Comment by Uppermost** [comment]
Caused by mve packet.

**Comment by chucktheripper** [comment]
Is this arleady fixed? I changed smth with mve

**Comment by Uppermost** [comment]
you can place any item in any eq or slot you want
so for example fairies in ETC
or chaos seeds in Wear
i won't open an issue because it's too easy to exploit and some ppl may find it out before you patch it
i mean it will probably take some time
packet 'mve' is not protected

(friends111 report)

Maybe it's fix chuck can you tell me?

**Comment by Uppermost** [comment]
No more information I close it.
