### ISSUE TITLE
add parser for teleporter target

### ISSUE THREAD

**Issue by MasterDomino** [OpenNos/OpenNos#288]
we need to find a way to parse target destination of teleporttype npc

**Comment by 0Lucifer0** [comment]
not a problem^^ but need to have all packet for this ;D

**Comment by Uppermost** [comment]
Packet here teleport map 170 to 189 ( Otherwise,everything is in packet.txt)
-----------------------------------------------------

npc_req 2 9411 452
mv 2 9410 76 21 4
stat 9530 9530 3885 3885 0 32
stat 9530 9530 3885 3885 0 32
eff 2 9411 857
mv 2 9408 25 30 4
mv 2 9407 27 104 4
mv 2 9405 98 59 4
st 2 9411 0 100 100 7 4
mv 2 9404 15 68 4
mv 2 9410 77 21 4
mv 2 9409 71 107 4
st 2 9411 0 100 100 7 4
mv 2 9404 14 67 4
gold 21990 0
c_map 0 170 0
mapout
c_info Uppermost - -1 5052 -Nemesis-(Membre) 626114 0 0 3 7 2 23 0 5 1 0 0 0
c_mode 1 626114 2406 0 0 0
equip 5 0 0.4903.5.0.0 2.340.0.0.0 5.4912.6.0.0 9.227.0.0.0 10.803.0.0.0 11.347.0.0.0 12.904.0.0.0 13.4146.0.0.0 14.4138.0.0.0
lev 92 527953756 24 245869 1225326000 252944 579979 3
stat 9530 9530 3885 3885 0 32
at 626114 189 58 164 2 0 63 1
cond 1 626114 0 0 20
c_map 0 189 1
sc 1 0 861 1009 953 14 190 0 0 783 839 792 16 350 0 104 195 115 195 93 10 7 4 20
gidx 1 626114 5052 -Nemesis-(Membre) 7
rsfp 0 -1
pairy 1 626114 4 4 0 0
pinit 0
