### ISSUE TITLE
SP chicken 0 damage

### ISSUE THREAD

**Issue by aerzy** [OpenNos/OpenNos#522]
when you hit monster 0 damage but when miss we see " miss "

![chiken](https://cloud.githubusercontent.com/assets/16693364/15012593/34288a8e-11fa-11e6-9725-4eeba76b83da.PNG)

![chikenmiss](https://cloud.githubusercontent.com/assets/16693364/15012604/53bb5c00-11fa-11e6-8905-56bf4ad1ad69.PNG)

**Comment by 0Lucifer0** [comment]
Damage system is not finished

**Comment by Ciapa1** [comment]
Do you use the latest commit? If not try it first, there may be a bug in a
older Version that caused that malfunction.
What equip do you use? Give us as many information as possible to reproduce
your Problem.
Am 04.05.2016 1:16 nachm. schrieb "aerzy" <notifications@github.com>:

when you hit monster 0 damage but when miss we see " miss "

[image: chiken]
<https://cloud.githubusercontent.com/assets/16693364/15012593/34288a8e-11fa-11e6-9725-4eeba76b83da.PNG>

[image: chikenmiss]
<https://cloud.githubusercontent.com/assets/16693364/15012604/53bb5c00-11fa-11e6-8905-56bf4ad1ad69.PNG>

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub
<https://github.com/OpenNos/OpenNos/issues/522>

**Comment by aerzy** [comment]
in screen 0 equipment but when i use bow not change yes i have last commit

**Comment by Ciapa1** [comment]
Equip a dagger and try again.
Am 04.05.2016 13:21 schrieb "aerzy" <notifications@github.com>:

**Comment by aerzy** [comment]
not change

**Comment by Ciapa1** [comment]
Does this happen when you change class to swordsman or magician?
Am 04.05.2016 13:29 schrieb "aerzy" <notifications@github.com>:

**Comment by aerzy** [comment]
not change

**Comment by earthnash** [comment]
same problem
![bugchicken](https://cloud.githubusercontent.com/assets/15151087/15015293/3e1406a0-1235-11e6-90fd-4c6b222d02a1.jpg)

**Comment by Ciapa1** [comment]
Other SP do damage?

**Comment by earthnash** [comment]
![wor](https://cloud.githubusercontent.com/assets/15151087/15015514/89833a2e-1236-11e6-912a-9eb40c6ff2bc.jpg)

**Comment by Ciapa1** [comment]
Writing that other SPS do damage would have been suficient ;)
However, seems like chicken hit is different from other hits, is it the
same for Pyjama, Pirate and Jajamaru? So that these don't do damage?

**Comment by earthnash** [comment]
pyjama and chicken only

**Comment by aerzy** [comment]
with the skill of cutting SP2 archer too

**Comment by Uppermost** [comment]
PS : Chicken sp never miss on official xD
