### ISSUE TITLE
Monster XP when attack by another player

### ISSUE THREAD

**Issue by Uppermost** [OpenNos/OpenNos#640]
When attacking a monster that has already been attacked by another player,

You will receive the packet: say playerID 10 You get only part of the experience because you did was defend yourself.

and so, you will only receive 50% experience.
- [ ] XP part and message to say it
- [x] Drop item part

**Comment by 0Lucifer0** [comment]
we need to add a damage list to mapmonster each mapmonster should know how much each people hit on them^^

**Comment by Uppermost** [comment]
Don't forget if player is in groupe objet is 1/2 for player and there is a share group you can drop all items whitout problem

**Comment by 0Lucifer0** [comment]
need to know you get this message when someone else hit how much ? 10% ?

**Comment by Uppermost** [comment]
Yes :)

**Comment by MasterDomino** [comment]
its more than just 10%, i guess around 50% maybe 30% damage needs to be done to monster for owner to be choosen, also ownage is removed after some time after dealing that 30%, i guess minute or just same as removal of ownage for items(3 minutes), after this time you only receive less exp because other player attacked the monster(50%) thats why i guess its around 50%

**Comment by Ciapa1** [comment]
Nothing to do with % damage the message, if someone else did the first hit and not in group with the person who killed it, the other person(who killed it) will receive the message and only receive 1/3 of the exp, the one who hittet first will get nothing then.
