### ISSUE TITLE
Review all act 4 cutscene

### ISSUE THREAD

**Issue by unknownforces** [OpenNos/OpenNos#825]
Uppermost edit :

We need to add the cutscene when you quit the act 4 and cutscene we you connect in act 4.

More informations on the packet : 

it 1 Nosville -> Act 4
it 2 When you login in Act 4
it 3 Act 4 -> Nosville

But they packet are not enough to display the animation and I don't know why.

**Comment by Uppermost** [comment]
Only on act 6 ? maybe not, cut scene is missing

**Comment by MasterDomino** [comment]
noo i think its the same problem we had

**Comment by 0Lucifer0** [comment]
need to compare with official ^^ uppermost try to get transport to act6 packet :)

**Comment by SC909** [comment]
Try with packet logger:
do this one first: c_map 0 228 1
after that do this one: c_map 0 1 1
if you try any other than c_map 0 1 1 it will do nothing, as I even tried c_map 0 145 1 (Port Alveus Square)

//to NosVille
c_map 0 228 0
mapout
c_map 0 1 1

//to Cylloan
c_map 0 1 0
mapout
c_map 0 228 1

I tried some other maps on act 6, I teleported from NosVille and from Port Alveus but the cutscene haven't appeared, when I teleported back to city using wings, it teleported me to Cylloan but still no cutscene. The cutscene is based on client so I don't think anything could be done.

**Comment by MasterDomino** [comment]
The problem here is that it could be some packet like evnt

**Comment by SC909** [comment]
I will have a closer look at it on OpenNos, as for the answer I posted it before:
1. Be in NosVille
2. Send to client: c_map 0 228 1

**Comment by SC909** [comment]
After some testing, it seems that the **client can't handle too many packets received**. (but I am not sure)
Packet eq should be sent only once when you log onto your character - not when you change maps.
Anyone who wants to test it, should try it on a clean server - **no npcs**, **no monsters**. Send packets by using packetlogger: **$Teleport 228 50 50** and then **$Teleport 1 50 50**. If you are lucky you will see the effect, but I recommend sending $Teleport 1 50 50 x2 or $Teleport 228 50 50 x2 or even try playing with it because I have send the same packet and it showed the cutscene 4 times (the same cutscene and the same packet)

I tried many things, but I think you need to:
Remove: **eq** (packet - when changing maps)
Add: **c_map id 0** (before sending mapout - when changing maps)
Add: a **delay** to other packets that are not so important at that time - on official its about 1 second (in packets and so on)

The best way to test it is just to send to client:
**at 1 1 50 50 2 0 74 -1
c_map 0 1 1**
and then
**at 1 228 50 50 2 0 74 -1
c_map 0 228 1** and it should work without any problems

**Comment by MasterDomino** [comment]
its exactly like official we dont care about additional packets, i used eq packet because its needed to refresh wigs properly which on official you receive when you wear wig lol it changes nothing if we add packets or remove them, maybe reordering would change something but for now i placed all required packets, need to wait until i get all packets that you receive on act4 to avelus

**Comment by SC909** [comment]
Seems to be working fine for act 6, but act 4 will be tricky as I tried some packets etc but with no results. It might be built into the client (like recv mz packet) but it doesn't do anything - but it is only an info from server e.g. you chose channel 1, but server checks it first if you are on act4 - if so then it will go through normal connection to channel 1, but after sending all necessary packets it will start sending it again.
So the official seems to transport the connection to another channel by using port forwarding.
The best way to find something out is to, travel to act 4, then do a relog - this will cause a black screen because of game_start I think. 

Playing with packets will give you nothing, as this might be something like NsCH which is not catched by packet logger. 
The only option is to wait until your team develops a multi channel support + port forwarding.
(I might be able to have a closer look - when Entwell will finally finish their patch for European servers)

**Comment by Uppermost** [comment]
act 6 cutscene seem's to work idk for act 5 but act 4 doesn't work

**Comment by Uppermost** [comment]
I try to fix that now I think we just need to send "it VALUE" packet.

**Comment by Martazza** [comment]
The packet that let us to see the cutscene is 
`**c_map  0 <MapId> <Show>**`
Where:
- **MapId** is the MapId of the map(1 - Nosville)
- **Show**: 1 Show cutscene, 0 don't show

**Comment by MasterDomino** [comment]
not 3rd value is used on exit of map if its 0 you exit the map if 1 you enter the map

**Comment by Uppermost** [comment]
It's for act 4 will be see later
