### ISSUE TITLE
Add option to turn $Speed off

### ISSUE THREAD

**Issue by unknownforces** [OpenNos/OpenNos#844]
Maybe something like $Speed 0 to turn it off?

**Comment by 0Lucifer0** [comment]
Just do $Speed 10

**Comment by unknownforces** [comment]
What about in the future when you get bonus speed from other things like wings, costume, boots, etc.

**Comment by 0Lucifer0** [comment]
Its already done Its absolutly not the same system >< when You remove sp You loose the sp speed when booster en You remove the booster speed Its only _+ but in the commande case You replace speed so You cant get back to old speed without keep It somewhere in a list of speed (because You can use Many Time the command) in case of vehicle we keep old speed because we cant use twice à vehicle we need to unwear It before reput It.

**Comment by unknownforces** [comment]
Ahh, I understand ^^
