### ISSUE TITLE
Problem with rarity stats

### ISSUE THREAD

**Issue by Uppermost** [OpenNos/OpenNos#993]
![image](https://cloud.githubusercontent.com/assets/15254478/18608548/c5e57916-7cec-11e6-8ab2-fd2c7425ca97.png)

PS : negative rarity have a problem always the same stat -2 -1 and R0 have the same stat

"Ok sorry you are right, but in your code it is wrong, I had a peak on OpenNos before posting anything.

You have a misplacement in your code
Your code is: return p * (1 + lvl / 5); 
and it should be: return p * (lvl / 5) +1; 

let's say it's lv 4 weapon, in your formula the result will be 1. So everytime it will be 1*rarity factor.
while it should be 1,8*rarity_factor. But at least you resolved that issue before me going through every piece of weapons and armours.

In a while I might go back and get more necessary info from moobs (how much Lvxp Jxp, and how much hp, mp each has as monster.dat will not tell you that.
And with some luck 'cause I am going through all GF servers. I will try and get you rarity factor for r8 as it is not constant value (not always the same). But the lv seems to be between 101 and 101,5.
"

**Comment by SC909** [comment]
R8
Hero Lv25: 252, 259, 282, 284, 293 and 297. (if you prefer it a different way then...)
Hero Lv25: 42, 49, 70, 72, 81, 85 (a difference between r7 and r8 - I have had a look at the most of r8 gear on all European servers)

R1 to R7
Hero Lv25 = Lv**101,25** (21, 42, 63, 85, 106, 148, 212)
Hero Lv28 = Lv**102** (21, 42, 64, 85, 107, 149, 214)

About the levels of Act 6.1
Level 101 won't work on Hero Lv25 because of ignoring decimal points.
(101 /5) +1 = 21,2 
21,2 * 4 = 84.8
And you can see above that it is 85.

r8 I think is a:
**Random number** generated between **40 and 90 or 1 and 100** but we don't know for sure,
or it might be:
**r8 = random(11, 15)** - as strengthening factor of 11 up to 15, from the formula.

I also have had a peak at NosTaleSE but their rarity system is different, none of r1 to r7 doesn't get any additional damage points like we do, and all the points in r8 on SE are placed in min or max damage
(as min damage will increase, or max damage).

I think the best approach will be to use random number generator between 1 and 100.
